title: Joseph Oluwaseun Peter # your name (or website title) here
logo: "/images/joseph.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Mobile Engineer
  <br><br>
  Android (java/kotlin), IOS (Swift), Flutter
  <br><br>
  <a href="https://www.linkedin.com/in/joseph-peter-535b0aa6/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: G-L4QLJ6JQYX # your Google Analytics tracking ID here
